version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: kfullstackdb
      POSTGRES_USER: kfullstackuser
      POSTGRES_PASSWORD: kfullstackpass
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./kfullstack
      dockerfile: Dockerfile
    container_name: kruger-backend
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=kfullstack
      - SERVER_CONTEXT_PATH=/kfullstack
      - SWAGGER_UI_PATH=/swagger-ui.html
      - SWAGGER_UI_FILTER=true
      - SWAGGER_API_TITLE=Sudamericana de Software
      - SWAGGER_API_DESCRIPTION=Microservicio de kfullstack
      - SWAGGER_API_VERSION=1.0
      - SWAGGER_API_EMAIL=info@sasf.net
      - SWAGGER_API_NAME=Sudamericana de Software
      - SWAGGER_API_PAGEURL=www.sasf.net
      - SWAGGER_API_URI=http://localhost:8080/kfullstack/
      - SWAGGER_API_DEV_URI=http://localhost:8080/kfullstack/
      - LOG_LEVEL=DEBUG
      - SPRING_PROFILE=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=kfullstackdb
      - DB_USERNAME=kfullstackuser
      - DB_PASSWORD=kfullstackpass
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - JPA_FORMAT_SQL=true
      - SERVER_PORT=8080
      - JWT_SECRET=SudamericanaDeSoftware1234567890123456
      - JWT_EXPIRATION=86400000
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./kfullstack-frontend
      dockerfile: Dockerfile
    container_name: kruger-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    
networks:
  app-network:
    driver: bridge